torch.tensor() 只支持一个参数，其功能将数据转换为张量，支持原生类型和 numpy 类型

In [2]:
import torch
import numpy as np
a = torch.tensor(5)
print(a)

anp = np.asarray([4])
a = torch.tensor(anp)
print(a)

tensor(5)
tensor([4])


torch.Tensor() 函数可以定义一个张量。在使用次函数定义张量时，可以指定张量的形状，也可以指定张量的内容

In [6]:
import torch
a = torch.Tensor(2)
print(a)

b = torch.Tensor(2, 3)
print(b)

c = torch.Tensor([2])
print(c)

d = torch.Tensor([2, 3])
print(d)

tensor([0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2.])
tensor([2., 3.])


torch.rand()可以生成随机初始化的张量

In [8]:
a = torch.rand(2,3)
print(a)

tensor([[4.2619e-01, 7.9750e-01, 6.1442e-01],
        [3.9339e-05, 8.9095e-01, 7.0454e-01]])


is_tensor() 判断是否为张量

In [9]:
a = torch.Tensor(2)
print(torch.is_tensor(a))

True


torch.numel()获得张量的元素个数

In [12]:
a = torch.Tensor(2, 3, 4)
print(torch.numel(a))

24


In [ ]:
import torch
a = torch.randn(4, 4)
print(a)
print('\n')
print(torch.max(a, 1))